#ifndef COMMON_H
#define COMMON_H


#define APPLE
#define MAX_BUFFER_SIZE 256

//相机位置
#define CAMERA_POSITION_X_INIT 0.0f
#define CAMERA_POSITION_Y_INIT 0.0f
#define CAMERA_POSITION_Z_INIT 1.0f

//相机朝向
#define CAMERA_DIRECTION_X_INIT 0.0f
#define CAMERA_DIRECTION_Y_INIT 0.0f
#define CAMERA_DIRECTION_Z_INIT -1.0f
#define CAMERA_UP_X_INIT 0.0f
#define CAMERA_UP_Y_INIT 1.0f
#define CAMERA_UP_Z_INIT 0.0f

#define CAMERA_SCALE_RATE 0.88

//Volume采样率，默认1.0
#define VOLUME_SAMPLINGRATE_INIT 1.0f

#define RENDER_WIDGET_WIDTH 768
#define RENDER_WIDGET_HEIGHT 768

#endif //COMMON_H
